import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Phase 4.1 — Convex as the document source of truth.
 *
 * Four tables model a document plus its FULL point-in-time history (§10.10c
 * standing directive: roll back to ANY version and view that state):
 *
 * - `documents`  — one row per email document. `headVersion` is a monotonic
 *   per-document version sequence: every applied operation (including undo/
 *   redo/revert entries, which are themselves new operations) increments it
 *   by exactly 1. Keyed to an anonymous `sessionId` (Phase 6.1 cleanup).
 * - `blocks`     — the CURRENT materialized state (head): one row per block
 *   of the flat EmailDocument map. Rewritten incrementally (diffed) on every
 *   mutation; reads assemble the flat map from these rows.
 * - `operations` — the append-only op log. Each row stores the small op JSON
 *   AND its exact inverse (generated by the SDK apply engine), plus
 *   provenance (author, caller, batch, thread) and undo bookkeeping.
 *   `version` is the document's headVersion after this op was applied, so
 *   (documentId, version) is unique and totally ordered.
 * - `snapshots`  — full flat EmailDocument JSON every SNAPSHOT_INTERVAL
 *   versions (plus version 0 at creation). doc-at-version V = nearest
 *   snapshot ≤ V + replay of the ops in between. A whole flat doc easily
 *   fits Convex's 1 MiB value limit at demo scale (a few dozen blocks, small
 *   rich-text payloads); revisit if documents ever approach hundreds of KB.
 *
 * The `op`, `inverse`, `doc`, and `properties` payloads are stored as
 * unvalidated JSON (`v.any()`) ON PURPOSE: their runtime guards are the
 * email-sdk Zod schemas (`operationSchema`, `emailDocumentSchema`, block
 * schemas), which every mutation runs through `applyOperation(s)` BEFORE
 * anything is written. Duplicating that discriminated union as Convex
 * validators would drift; the SDK is the single source of shape truth.
 */

/** Mirrors email-sdk BLOCK_TYPES (kept literal so the schema stays dependency-free). */
const blockTypeValidator = v.union(
  v.literal("root"),
  v.literal("section"),
  v.literal("row"),
  v.literal("column"),
  v.literal("text"),
  v.literal("button"),
  v.literal("image"),
  v.literal("divider"),
  v.literal("link"),
  v.literal("code"),
  v.literal("spacer"),
);

/** Mirrors email-sdk OPERATION_AUTHORS. */
export const operationAuthorValidator = v.union(v.literal("user"), v.literal("agent"));

/** Mirrors email-sdk ACTION_CALLERS. */
export const actionCallerValidator = v.union(
  v.literal("tool"),
  v.literal("http"),
  v.literal("frontend"),
  v.literal("cli"),
  v.literal("mcp"),
);

/** A flat EmailDocument (blockId → block JSON). Runtime guard: emailDocumentSchema (Zod). */
export const emailDocumentValidator = v.record(v.string(), v.any());

export default defineSchema({
  /**
   * The shareable/multiplayer unit and future chat-thread scope (§10.10b
   * "multiple drafts on one canvas"). A canvas holds one or more document
   * drafts; the feature UI lands later, the shape exists from day one.
   */
  canvases: defineTable({
    /** Anonymous owner session (localStorage id). Phase 6.1 keys cleanup off this. */
    sessionId: v.string(),
    title: v.optional(v.string()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  }).index("by_sessionId", ["sessionId"]),

  /** One row = one draft instance on a canvas, with its own independent version history. */
  documents: defineTable({
    canvasId: v.id("canvases"),
    /** Denormalized from the canvas for direct per-session listing/cleanup. */
    sessionId: v.string(),
    /** USER-FACING draft name ("Draft 1"): human-editable, never edited by the agent. */
    name: v.string(),
    /**
     * AGENT-FACING draft name: an agent-authored semantic summary of the
     * draft's content ("Spring sale — bold hero, single CTA"), maintained
     * ASYNCHRONOUSLY off the LLM hot path and persisted here. Read-only to
     * users (may be displayed, never edited). Exists because human-authored
     * names can be unhelpful for disambiguation ("asdf", "v2 final FINAL");
     * the agent resolves references like "draft two" against BOTH names,
     * with the stable document id as the true key. (§10.2 dual-naming.)
     */
    agentName: v.optional(v.string()),
    /** Placement on the canvas (ascending; fractional values allowed for insert-between). */
    orderIndex: v.number(),
    /** Monotonic per-document version; version N = state after operation row N. */
    headVersion: v.number(),
    /** Lineage: set when this draft was duplicated from another (Figma-style fork, not a git branch). */
    forkedFromDocumentId: v.optional(v.id("documents")),
    forkedFromVersion: v.optional(v.number()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  })
    .index("by_sessionId", ["sessionId"])
    .index("by_canvasId", ["canvasId"])
    // Phase 6.1 cleanup cron: range-scan for stale documents. `updatedAtMs`
    // is the last-activity signal — commitVersions patches it on EVERY
    // committed operation (all write paths funnel through it).
    .index("by_updatedAtMs", ["updatedAtMs"]),

  blocks: defineTable({
    documentId: v.id("documents"),
    /** email-sdk block id ("root", "sec_a1b2", ...). NOT the Convex row id. */
    blockId: v.string(),
    type: blockTypeValidator,
    parentId: v.union(v.string(), v.null()),
    childrenIds: v.array(v.string()),
    /** Block properties JSON. Runtime guard: the per-type email-sdk block schemas. */
    properties: v.record(v.string(), v.any()),
  })
    .index("by_documentId", ["documentId"])
    .index("by_documentId_and_blockId", ["documentId", "blockId"]),

  operations: defineTable({
    documentId: v.id("documents"),
    /** 1..N, dense and unique per document (assigned under the mutation's transaction). */
    version: v.number(),
    /** The applied operation JSON. Runtime guard: operationSchema (Zod). */
    op: v.any(),
    /** The exact inverse generated by the SDK when `op` was applied. */
    inverse: v.any(),
    /** Stable author identifier: anonymous session id, or agent/thread id for AI edits. */
    authorId: v.string(),
    author: operationAuthorValidator,
    caller: actionCallerValidator,
    /** Groups ops applied atomically as one batch (e.g. one AI turn). */
    batchId: v.optional(v.string()),
    threadId: v.optional(v.string()),
    /**
     * History bookkeeping:
     * - "edit": a normal forward operation (the only kind undo targets).
     * - "undo": applies the inverse of the edit at `undoesVersion`.
     * - "redo": re-applies an undone edit by inverting the undo at `redoesVersion`.
     */
    kind: v.union(v.literal("edit"), v.literal("undo"), v.literal("redo")),
    undoesVersion: v.optional(v.number()),
    redoesVersion: v.optional(v.number()),
    /** Set on an "edit" (or "undo") row when a later op reversed it. */
    isUndone: v.optional(v.boolean()),
    undoneByVersion: v.optional(v.number()),
    createdAtMs: v.number(),
  })
    .index("by_documentId_and_version", ["documentId", "version"])
    .index("by_documentId_and_batchId", ["documentId", "batchId"])
    .index("by_documentId_and_authorId", ["documentId", "authorId"]),

  /**
   * Demo-mode ghost collaborator (convex/ghost.ts): at most one row per
   * document while a ghost typing session is live; deleted when the session
   * finishes or is stopped. `generation` (the session's start timestamp)
   * stamps every scheduled tick so stale ticks from a superseded session
   * self-cancel. Rows are transient by design — a chain that dies leaves a
   * row that the STALE_GHOST_SESSION_MS guard treats as not-running and the
   * next startGhost sweeps.
   */
  ghostSessions: defineTable({
    documentId: v.id("documents"),
    /** The text block the ghost is typing into. */
    blockId: v.string(),
    /** Session nonce (start timestamp); ticks with a different one self-cancel. */
    generation: v.number(),
    /** The full message the ghost types, character by character. */
    script: v.string(),
    /** Script index where the ghost mistypes once (-1 = no typo step). */
    typoIndex: v.number(),
    /** The wrong character typed at typoIndex (then backspaced). */
    typoChar: v.string(),
    /** Next keystroke-plan step to apply (0 .. script.length [+2 with typo]). */
    planIndex: v.number(),
    /** Flattened tail of the block's text at start — the content anchor. */
    anchorTail: v.string(),
    startedAtMs: v.number(),
  }).index("by_documentId", ["documentId"]),

  /**
   * Multi-agent canvas v0 (docs/proposals/multi-agent-canvas.md §3.1): the
   * persona registry. A persona is PURE DATA — behavior lives entirely in
   * `personaMarkdown` (+ the typed capability/cooldown fields); no
   * persona-conditional code path may ever branch on a slug (§4.6, the
   * marketplace invariant). Built-ins are seeded idempotently by
   * personas.seedBuiltInPersonas.
   *
   * v1 SEAM (editing personas): widen `capabilityMode` to
   * v.union(v.literal("advisory"), v.literal("editing")) and add a dispatch
   * path that routes persona tool calls through the SAME validated mutations
   * as the chat agent (documents.applyOperations / agentText.*). Until then
   * the literal type IS the server-side enforcement: an "editing" persona row
   * cannot exist, and no code dispatches ops on a persona's behalf — advisory
   * findings are applied only by a human clicking Apply in the suggestions UI.
   *
   * v1 COPY-ON-EDIT (proposal §6 item 9): built-ins are never edited in
   * place. Saving an edit to a built-in forks a SESSION COPY — slug
   * `user/<sessionId>/<base>` shadowing `builtin/<base>` in that session's
   * picker (the deterministic slug scheme means at most one copy per
   * built-in per session; personas.ts owns the convention). Copies are
   * ordinary registry rows, so presence/runner plumbing needs no changes.
   */
  agents: defineTable({
    /** Stable namespaced id ("builtin/tone-police"); third-party namespaces later. */
    slug: v.string(),
    /** Display name shown in the facepile / picker / suggestion cards. */
    name: v.string(),
    /** Presence + card accent color (distinct from human hue wheel & agent violet). */
    color: v.string(),
    /** Server-enforced capability: advisory personas have NO dispatch path. */
    capabilityMode: v.literal("advisory"),
    /**
     * THE BEHAVIOR: frontmatter-ish header (display metadata) + freeform
     * conduct text, injected as a prompt layer by /api/personas. User-editable
     * in-app (v1); edits to built-ins fork a session copy (see above).
     */
    personaMarkdown: v.string(),
    /** Minimum seconds between runner turns for this persona (budget guard). */
    cooldownSeconds: v.number(),
    /** True for seeded registry rows (pristine; edits fork a session copy). */
    isBuiltIn: v.boolean(),
    /** Owning anonymous session (localStorage id) for user copies; absent on built-ins. */
    createdBySessionId: v.optional(v.string()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  })
    .index("by_slug", ["slug"])
    .index("by_createdBySessionId", ["createdBySessionId"]),

  /**
   * The per-session brand kit (Phase 7.x brand kit panel): at most ONE active
   * kit per anonymous session in v1 — saveBrandKit replaces any existing row.
   * Every canvas/tab of the session reads the same kit reactively
   * (getActiveBrandKit), falling back to the frontend MOCK_BRAND_KIT when no
   * row exists. `variations[].globals` is unvalidated JSON on purpose (same
   * policy as ops/blocks above): its runtime guards are the email-sdk
   * `globalStylesSchema` (Zod, strict) plus the shared WCAG contrast check in
   * convex/brandKits.ts, both run BEFORE anything is written.
   *
   * NOTE (Phase 6.1 cleanup cron): the cron reaps stale DOCUMENTS only —
   * brandKits rows are keyed to sessions, not documents, and are NOT reaped
   * yet. They're tiny (one small JSON row per browser session); revisit if a
   * session-level cleanup pass ever lands.
   */
  brandKits: defineTable({
    /** Anonymous owner session (localStorage id) — the "user" this kit belongs to. */
    sessionId: v.string(),
    /** Brand name (scraped or user-provided). */
    name: v.string(),
    /** The scraped website, when the kit came from the generate pipeline. */
    sourceUrl: v.optional(v.string()),
    /** Email-safe CSS font stacks the kit was built around. */
    fonts: v.object({ heading: v.string(), body: v.string() }),
    /**
     * Monotonic save counter (brand-kit architecture §3.2): bumped by every
     * patch-in-place save and by asset confirm/remove (meaningful diffs);
     * NOT by name-only renames. `(kitId, revision)` is what Stage M draft
     * pointers compare against. Optional for pre-Stage-S rows — absent
     * means revision 1 (normalized by getEffectiveRevision).
     */
    revision: v.optional(v.number()),
    /**
     * Brand logo: extraction suggestion (absolute URL or data:image/svg+xml
     * URI) until confirmed, then OVERWRITTEN with the durable Convex storage
     * serving URL. Confirmed-only may enter documents (owner decision 4) —
     * gate via getConfirmedBrandAssetUrl, never read this field directly
     * from document-writing code.
     */
    logoUrl: v.optional(v.string()),
    /** Set on confirm: the uploaded logo binary (deleted on replace/clear). */
    logoStorageId: v.optional(v.id("_storage")),
    /** Provenance: the original scraped URL the confirmed binary came from. */
    logoSourceUrl: v.optional(v.string()),
    logoConfirmedAtMs: v.optional(v.number()),
    /** og:image social-card URL — same suggestion→confirmed lifecycle as logo. */
    socialImageUrl: v.optional(v.string()),
    socialImageStorageId: v.optional(v.id("_storage")),
    socialImageSourceUrl: v.optional(v.string()),
    socialImageConfirmedAtMs: v.optional(v.number()),
    /**
     * The brand's social profile links (item 26): one per platform (x,
     * facebook, instagram, …), deterministically extracted and SSRF-guarded.
     * Replaced wholesale by each save (revision bumps with every save).
     */
    socialLinks: v.optional(v.array(v.object({ platform: v.string(), url: v.string() }))),
    /** ThemeVariation[]: complete `Required<GlobalStyles>` payloads (see guard note above). */
    variations: v.array(
      v.object({
        id: v.string(),
        name: v.string(),
        globals: v.record(v.string(), v.any()),
      }),
    ),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  }).index("by_sessionId", ["sessionId"]),

  /**
   * Content Studio Stage S: the per-session image library. One row = one
   * OWNED storage file. Registration at upload time is MANDATORY for all new
   * uploads (docs/proposals/content-studio.md §4) — this table is the system
   * of record for storage-file ownership: the document-deletion cascade
   * RETAINS any file with a row here (model/cleanup.ts §6.1), so a registered
   * asset outlives the drafts it was used in ("the image I uploaded
   * yesterday"). Unregistered legacy files keep the old cascade behavior
   * until the Stage M backfill registers them.
   *
   * NOTE (cleanup): like brandKits, asset rows are session-keyed and NOT
   * reaped by the document cron. Stage L adds the dead-session sweep
   * (assets whose session owns no documents and are >30 days old).
   */
  assets: defineTable({
    /** Anonymous owner session (localStorage id) — the "user" (same key as brandKits). */
    sessionId: v.string(),
    storageId: v.id("_storage"),
    /**
     * Durable serving URL, denormalized at registration (stable for the
     * file's lifetime; also the join key against block `src` strings, which
     * store plain URLs by design — the SDK has no Convex coupling).
     */
    url: v.string(),
    /** Provenance kind — the library's filter axis. Widens later ("scraped"). */
    kind: v.union(
      v.literal("uploaded"),
      v.literal("generated"),
      v.literal("logo"),
      v.literal("social-card"),
    ),
    /** Human-editable display name; seeded per kind (filename / prompt stem / kit name). */
    name: v.string(),
    /** Denormalized from the _storage system doc at registration (grid display). */
    mimeType: v.optional(v.string()),
    sizeBytes: v.optional(v.number()),
    /** kind:"generated" — the prompt (rerun/regenerate affordances later). */
    prompt: v.optional(v.string()),
    /** Model- or user-authored alt text; inserted alongside src. */
    alt: v.optional(v.string()),
    /** kind:"logo"/"social-card" — the scrape origin (brand-kit provenance). */
    sourceUrl: v.optional(v.string()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  })
    .index("by_sessionId", ["sessionId"])
    .index("by_storageId", ["storageId"])
    .index("by_url", ["url"]),

  /**
   * Multi-agent canvas v1 — PERSISTED advisory persona findings (proposal
   * §3.6 client-merge sketch, §5.6b turn-input dedup). One row = one finding
   * from the batched /api/personas runner. Persisting (instead of returning
   * findings only to the initiating client) is what makes findings CROSS-TAB
   * and CROSS-COLLABORATOR: every tab's suggestion surface reads the same
   * open rows reactively, and a dismissal or apply in any tab converges
   * everywhere. This table is also the §10 row-1 "suggestion queue" starting
   * to exist, and the runner reads a persona's own open rows back as prompt
   * context so it never re-flags what it already flagged (§5.6b).
   *
   * Shape invariants:
   * - `ops` is unvalidated JSON ON PURPOSE (the ops/blocks column policy in
   *   the header note): its runtime guard is the email-sdk Zod schemas — the
   *   runner composes ops via `updateBlockPropertiesOperationSchema` and
   *   dry-runs the batch through pure `applyOperations` BEFORE recording, and
   *   the client dry-runs again at Apply time. An EMPTY array is legal and
   *   means an informational finding (dismiss only, no Apply).
   * - `targetSnapshots` maps blockId → stableStringify(block) (the client's
   *   key-order-insensitive staleness serializer, shared via
   *   apps/web/src/lib/suggestions/serialize-block.ts), computed from the
   *   SAME doc snapshot the ops were dry-run against. It covers every
   *   `targetBlockIds` entry PLUS every block the ops touch, so "no snapshot
   *   drifted" implies "the ops still apply". A finding whose snapshot
   *   drifts is STALE and dies quietly: each client hides it against its own
   *   rendered doc (converges without any mutation, so applies never race),
   *   and the runner deletes stale open rows before assembling its dedup
   *   context.
   * - Persona identity (name/color) is denormalized from the `agents` row at
   *   recording time so cards render without a registry join; the slug stays
   *   the stable key.
   * - Lifecycle is one-way: open → dismissed | applied. A dismissed row also
   *   blocks re-recording the same `patternKey` (the runner skips it), which
   *   is the server-side twin of the client's localStorage dismissal keys.
   *   `appliedBatchId` links an applied row to its op-log batch (the ops
   *   themselves live in `operations` with `persona:<slug>` provenance —
   *   applying goes through the ONE history spine, never a new write path).
   */
  personaFindings: defineTable({
    documentId: v.id("documents"),
    /** Registry slug of the persona that produced this finding. */
    personaSlug: v.string(),
    /** Denormalized persona identity for the card chip (see note above). */
    personaName: v.string(),
    personaColor: v.string(),
    /** Dismissal identity: `persona:${slug}|${sorted targetBlockIds}` (types.ts). */
    patternKey: v.string(),
    title: v.string(),
    description: v.string(),
    /** Visible content references ("the button labeled 'Buy now'") — never ids. */
    targetBlockNames: v.array(v.string()),
    /** email-sdk block ids this finding depends on (staleness scope). */
    targetBlockIds: v.array(v.string()),
    /** Pre-validated updateBlockProperties ops JSON; empty = informational. */
    ops: v.array(v.any()),
    /**
     * Main-agent handoff for OP-LESS findings: a ready-to-send chat prompt in
     * the user's voice ("Ask in chat" inserts it into the composer — never
     * auto-sent). Absent on findings with ops and on rows recorded before the
     * field existed (those render without the handoff CTA).
     */
    suggestedPrompt: v.optional(v.string()),
    /** blockId → stableStringify(block) at recording time (staleness baseline). */
    targetSnapshots: v.record(v.string(), v.string()),
    status: v.union(v.literal("open"), v.literal("dismissed"), v.literal("applied")),
    /** The op-log batchId of the human's apply (set with status "applied"). */
    appliedBatchId: v.optional(v.string()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  })
    .index("by_documentId", ["documentId"])
    .index("by_documentId_and_status", ["documentId", "status"]),

  /**
   * Saved reusable sections: a user bookmarks a section they've customized
   * (footer with their details, header with their logo, an article layout)
   * and re-inserts it into any draft later. Session-scoped like `assets` —
   * the same demoable-identity model: one anonymous browser session owns its
   * saved list, readable from every canvas/draft of that session.
   *
   * `blocks` is the section's SUBTREE as a flat list in the restoreBlocks
   * shape (section root FIRST, every descendant's parentId pointing into the
   * list) and is unvalidated JSON per the ops/blocks column policy above:
   * the runtime guard is the email-sdk Zod blockSchema + subtree-closure
   * check run by savedSections.save BEFORE the row is written. Saved rows
   * keep their ORIGINAL ids — fresh ids are minted at INSERT time (the
   * duplicate-block pattern), so one saved section inserts many times safely.
   */
  savedSections: defineTable({
    /** Anonymous owner session (localStorage id) — same key as assets/brandKits. */
    sessionId: v.string(),
    /** Human-editable display name, seeded from the section's first text. */
    name: v.string(),
    /** Flat subtree, root first (restoreBlocks shape). Runtime guard: email-sdk Zod on save. */
    blocks: v.array(v.any()),
    /** Denormalized blocks.length for list cards (avoids shipping counts client-side). */
    blockCount: v.number(),
    /**
     * LLM-authored selection guidance (the catalog templates' useWhen
     * analogue): when to reach for this section while composing. Written
     * ASYNCHRONOUSLY after save by the fails-soft enrichment call
     * (/api/saved-sections/enrich) — absent until it lands (or forever, if
     * enrichment failed; the row works fine without it).
     */
    useWhen: v.optional(v.string()),
    /** LLM-authored structural summary (layout + content inventory), same lifecycle. */
    description: v.optional(v.string()),
    /** Inserts to date (palette, manager modal, agent) — a prompt TIEBREAKER, never a ranker. */
    useCount: v.optional(v.number()),
    lastUsedAtMs: v.optional(v.number()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  }).index("by_sessionId", ["sessionId"]),

  snapshots: defineTable({
    documentId: v.id("documents"),
    /** The headVersion this snapshot captures (0 = the freshly created document). */
    version: v.number(),
    /** Full flat EmailDocument JSON. Runtime guard: emailDocumentSchema (Zod). */
    doc: emailDocumentValidator,
    createdAtMs: v.number(),
  }).index("by_documentId_and_version", ["documentId", "version"]),
});
