import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Phase 4.1 — Convex as the document source of truth.
 *
 * Four tables model a document plus its FULL point-in-time history (§10.10c
 * standing directive: roll back to ANY version and view that state):
 *
 * - `documents`  — one row per email document. `headVersion` is a monotonic
 *   per-document version sequence: every applied operation (including undo/
 *   redo/revert entries, which are themselves new operations) increments it
 *   by exactly 1. Keyed to an anonymous `sessionId` (Phase 6.1 cleanup).
 * - `blocks`     — the CURRENT materialized state (head): one row per block
 *   of the flat EmailDocument map. Rewritten incrementally (diffed) on every
 *   mutation; reads assemble the flat map from these rows.
 * - `operations` — the append-only op log. Each row stores the small op JSON
 *   AND its exact inverse (generated by the SDK apply engine), plus
 *   provenance (author, caller, batch, thread) and undo bookkeeping.
 *   `version` is the document's headVersion after this op was applied, so
 *   (documentId, version) is unique and totally ordered.
 * - `snapshots`  — full flat EmailDocument JSON every SNAPSHOT_INTERVAL
 *   versions (plus version 0 at creation). doc-at-version V = nearest
 *   snapshot ≤ V + replay of the ops in between. A whole flat doc easily
 *   fits Convex's 1 MiB value limit at demo scale (a few dozen blocks, small
 *   rich-text payloads); revisit if documents ever approach hundreds of KB.
 *
 * The `op`, `inverse`, `doc`, and `properties` payloads are stored as
 * unvalidated JSON (`v.any()`) ON PURPOSE: their runtime guards are the
 * email-sdk Zod schemas (`operationSchema`, `emailDocumentSchema`, block
 * schemas), which every mutation runs through `applyOperation(s)` BEFORE
 * anything is written. Duplicating that discriminated union as Convex
 * validators would drift; the SDK is the single source of shape truth.
 */

/** Mirrors email-sdk BLOCK_TYPES (kept literal so the schema stays dependency-free). */
const blockTypeValidator = v.union(
  v.literal("root"),
  v.literal("section"),
  v.literal("row"),
  v.literal("column"),
  v.literal("text"),
  v.literal("button"),
  v.literal("image"),
  v.literal("divider"),
);

/** Mirrors email-sdk OPERATION_AUTHORS. */
export const operationAuthorValidator = v.union(v.literal("user"), v.literal("agent"));

/** Mirrors email-sdk ACTION_CALLERS. */
export const actionCallerValidator = v.union(
  v.literal("tool"),
  v.literal("http"),
  v.literal("frontend"),
  v.literal("cli"),
  v.literal("mcp"),
);

/** A flat EmailDocument (blockId → block JSON). Runtime guard: emailDocumentSchema (Zod). */
export const emailDocumentValidator = v.record(v.string(), v.any());

export default defineSchema({
  /**
   * The shareable/multiplayer unit and future chat-thread scope (§10.10b
   * "multiple drafts on one canvas"). A canvas holds one or more document
   * drafts; the feature UI lands later, the shape exists from day one.
   */
  canvases: defineTable({
    /** Anonymous owner session (localStorage id). Phase 6.1 keys cleanup off this. */
    sessionId: v.string(),
    title: v.optional(v.string()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  }).index("by_sessionId", ["sessionId"]),

  /** One row = one draft instance on a canvas, with its own independent version history. */
  documents: defineTable({
    canvasId: v.id("canvases"),
    /** Denormalized from the canvas for direct per-session listing/cleanup. */
    sessionId: v.string(),
    /** USER-FACING draft name ("Draft 1"): human-editable, never edited by the agent. */
    name: v.string(),
    /**
     * AGENT-FACING draft name: an agent-authored semantic summary of the
     * draft's content ("Spring sale — bold hero, single CTA"), maintained
     * ASYNCHRONOUSLY off the LLM hot path and persisted here. Read-only to
     * users (may be displayed, never edited). Exists because human-authored
     * names can be unhelpful for disambiguation ("asdf", "v2 final FINAL");
     * the agent resolves references like "draft two" against BOTH names,
     * with the stable document id as the true key. (§10.2 dual-naming.)
     */
    agentName: v.optional(v.string()),
    /** Placement on the canvas (ascending; fractional values allowed for insert-between). */
    orderIndex: v.number(),
    /** Monotonic per-document version; version N = state after operation row N. */
    headVersion: v.number(),
    /** Lineage: set when this draft was duplicated from another (Figma-style fork, not a git branch). */
    forkedFromDocumentId: v.optional(v.id("documents")),
    forkedFromVersion: v.optional(v.number()),
    createdAtMs: v.number(),
    updatedAtMs: v.number(),
  })
    .index("by_sessionId", ["sessionId"])
    .index("by_canvasId", ["canvasId"])
    // Phase 6.1 cleanup cron: range-scan for stale documents. `updatedAtMs`
    // is the last-activity signal — commitVersions patches it on EVERY
    // committed operation (all write paths funnel through it).
    .index("by_updatedAtMs", ["updatedAtMs"]),

  blocks: defineTable({
    documentId: v.id("documents"),
    /** email-sdk block id ("root", "sec_a1b2", ...). NOT the Convex row id. */
    blockId: v.string(),
    type: blockTypeValidator,
    parentId: v.union(v.string(), v.null()),
    childrenIds: v.array(v.string()),
    /** Block properties JSON. Runtime guard: the per-type email-sdk block schemas. */
    properties: v.record(v.string(), v.any()),
  })
    .index("by_documentId", ["documentId"])
    .index("by_documentId_and_blockId", ["documentId", "blockId"]),

  operations: defineTable({
    documentId: v.id("documents"),
    /** 1..N, dense and unique per document (assigned under the mutation's transaction). */
    version: v.number(),
    /** The applied operation JSON. Runtime guard: operationSchema (Zod). */
    op: v.any(),
    /** The exact inverse generated by the SDK when `op` was applied. */
    inverse: v.any(),
    /** Stable author identifier: anonymous session id, or agent/thread id for AI edits. */
    authorId: v.string(),
    author: operationAuthorValidator,
    caller: actionCallerValidator,
    /** Groups ops applied atomically as one batch (e.g. one AI turn). */
    batchId: v.optional(v.string()),
    threadId: v.optional(v.string()),
    /**
     * History bookkeeping:
     * - "edit": a normal forward operation (the only kind undo targets).
     * - "undo": applies the inverse of the edit at `undoesVersion`.
     * - "redo": re-applies an undone edit by inverting the undo at `redoesVersion`.
     */
    kind: v.union(v.literal("edit"), v.literal("undo"), v.literal("redo")),
    undoesVersion: v.optional(v.number()),
    redoesVersion: v.optional(v.number()),
    /** Set on an "edit" (or "undo") row when a later op reversed it. */
    isUndone: v.optional(v.boolean()),
    undoneByVersion: v.optional(v.number()),
    createdAtMs: v.number(),
  })
    .index("by_documentId_and_version", ["documentId", "version"])
    .index("by_documentId_and_batchId", ["documentId", "batchId"])
    .index("by_documentId_and_authorId", ["documentId", "authorId"]),

  /**
   * Demo-mode ghost collaborator (convex/ghost.ts): at most one row per
   * document while a ghost typing session is live; deleted when the session
   * finishes or is stopped. `generation` (the session's start timestamp)
   * stamps every scheduled tick so stale ticks from a superseded session
   * self-cancel. Rows are transient by design — a chain that dies leaves a
   * row that the STALE_GHOST_SESSION_MS guard treats as not-running and the
   * next startGhost sweeps.
   */
  ghostSessions: defineTable({
    documentId: v.id("documents"),
    /** The text block the ghost is typing into. */
    blockId: v.string(),
    /** Session nonce (start timestamp); ticks with a different one self-cancel. */
    generation: v.number(),
    /** The full message the ghost types, character by character. */
    script: v.string(),
    /** Script index where the ghost mistypes once (-1 = no typo step). */
    typoIndex: v.number(),
    /** The wrong character typed at typoIndex (then backspaced). */
    typoChar: v.string(),
    /** Next keystroke-plan step to apply (0 .. script.length [+2 with typo]). */
    planIndex: v.number(),
    /** Flattened tail of the block's text at start — the content anchor. */
    anchorTail: v.string(),
    startedAtMs: v.number(),
  }).index("by_documentId", ["documentId"]),

  snapshots: defineTable({
    documentId: v.id("documents"),
    /** The headVersion this snapshot captures (0 = the freshly created document). */
    version: v.number(),
    /** Full flat EmailDocument JSON. Runtime guard: emailDocumentSchema (Zod). */
    doc: emailDocumentValidator,
    createdAtMs: v.number(),
  }).index("by_documentId_and_version", ["documentId", "version"]),
});
